const equipment=[
['Refugio y montaje',[
['tienda','Tienda de campaña','Esencial','grupo','El refugio protege de lluvia, viento e insectos.','Elige capacidad útil para las personas y su equipo; revisa ventilación, altura y espacio de montaje. La capacidad nominal no siempre deja espacio para equipaje.','Prueba el montaje en casa, revisa costuras y lleva todas las varillas. Guarda la tienda completamente seca.'],
['estacas','Estacas, vientos y mazo','Esencial','grupo','Mantienen el refugio estable y ayudan a tensar el doble techo.','Verifica que las estacas sean adecuadas al suelo permitido del camping y compatibles con la tienda.','Cuenta las piezas y revisa cuerdas y tensores antes de salir.'],
['suelo','Protector de suelo','Según la salida','grupo','Ayuda a proteger la base de la tienda.','Debe ajustarse a la huella de la tienda sin sobresalir y recoger agua.','No reemplaza la elección de un emplazamiento adecuado.'],
['sombra','Toldo o sombra','Según la salida','grupo','Da un espacio protegido para convivir.','Revisa tamaño, anclajes y restricciones de montaje del camping.','Evalúa el viento; no cocines dentro de la tienda ni en espacios cerrados.']]],
['Sistema de descanso',[
['saco','Saco de dormir o ropa de cama','Esencial','persona','El descanso condiciona toda la experiencia.','Elige según las condiciones nocturnas previstas y el conjunto de abrigo y aislamiento, no solo por el clima diurno.','Revisa el pronóstico del destino; si no lo conoces, deja la elección pendiente.'],
['colchon','Colchón, catre o aislante','Esencial','persona','Separa el cuerpo del suelo y aporta comodidad; el aislamiento depende del modelo.','Comprueba espacio en la tienda y aislamiento térmico. Un colchón alto no es necesariamente cálido.','Pruébalo antes, revisa fugas y compatibilidad con el inflador.'],
['almohada','Almohada','Confort','persona','Facilita dormir con una postura habitual.','En camping con coche puedes usar una de casa si cabe bien y se mantiene seca.','Guárdala protegida de humedad.'],
['inflador','Inflador y reparación del colchón','Según la salida','grupo','Permiten preparar y mantener un colchón inflable.','Comprueba válvula, alimentación y repuestos específicos.','Marca No aplica si no llevas equipo inflable.']]],
['Ropa y calzado',[
['bolsa-ropa','Maleta, bolsa o mochila para ropa','Esencial','persona','Transporta y organiza la ropa personal entre casa, vehículo y campamento. No es necesario llevar los tres tipos de equipaje: elige el que mejor se adapte a tu salida.','Prioriza un formato que quepa en el vehículo y en la tienda, con apertura cómoda y asas resistentes. Una bolsa flexible puede aprovechar mejor el espacio. Si habrá humedad, protege el contenido con bolsas interiores impermeables.','Separa ropa limpia, sucia y mojada. Deja accesibles el abrigo y el impermeable. Puedes compartir una maleta entre varios integrantes: ajusta la cantidad y asigna un responsable.'],
['mochila-dia','Mochila de ataque o senderismo','Según la salida','persona','Mochila pequeña para caminatas de día desde el campamento base. Permite llevar lo necesario sin cargar la maleta o bolsa de ropa.','Elige tamaño y ajuste según la duración, el recorrido y el equipo que llevarás. Comprueba comodidad con carga, tirantes y acceso al agua. No necesitas una mochila de travesía grande para una caminata corta.','Prepara agua, alimento, abrigo o impermeable, frontal y los elementos de orientación y auxilio que requiera la ruta. No los dejes en el coche si los necesitarás en el recorrido. Ajusta cantidades por integrante y marca No aplica si no realizarás excursiones ni necesitas una mochila de día.'],
['capas','Ropa por capas y abrigo','Esencial','persona','Permite ajustar el abrigo a los cambios de temperatura.','Selecciona capas de acuerdo con clima, actividad y noches de estancia.','Cuenta las prendas por persona; ajusta los cambios según duración y posibilidad de secado.'],
['lluvia','Impermeable','Esencial','persona','Protección personal frente a lluvia y viento.','Revisa cobertura, talla y estado del material antes de empacar.','Tenlo accesible durante el trayecto y al llegar.'],
['calzado','Calzado y calcetines de repuesto','Esencial','persona','Para caminar por el campamento y las excursiones previstas.','Usa calzado conocido y adecuado al terreno.','Empaca los repuestos en una bolsa seca.'],
['sol','Sombrero y protección solar','Esencial','persona','Protección para actividades al aire libre.','Considera sombra, ropa de cobertura y productos adecuados para cada integrante.','Sigue las indicaciones del producto y las necesidades personales.']]],
['Agua y alimentación',[
['agua','Agua y recipientes','Esencial','grupo','Resuelve bebida, preparación de alimentos y necesidades del campamento.','Confirma si hay agua potable y planifica cantidad según personas, duración, clima y posibilidad de reabastecer.','No des por hecho que el agua del sitio es potable. Anota los litros previstos en las notas.'],
['tratamiento','Sistema de tratamiento de agua','Según la salida','grupo','Puede ser necesario si dependerás de fuentes sin potabilidad confirmada.','Elige un método adecuado a la fuente y sigue las instrucciones del fabricante.','La app lo destaca mientras no se confirme agua potable; no sustituye investigar la fuente.'],
['comida','Alimentos y menú','Esencial','grupo','Planificar evita olvidos y reduce desperdicios.','Organiza las comidas por día y persona, considerando alergias y restricciones alimentarias.','Anota menú, porciones y productos que empacarás al final.'],
['nevera','Hielera o nevera y acumuladores de frío','Según la salida','grupo','Necesarios cuando el menú incluye alimentos que requieren refrigeración.','Dimensiona según alimentos, duración y acceso a hielo o electricidad.','Mantén la cadena de frío según las indicaciones de conservación de los alimentos.']]],
['Cocina',[
['estufa','Estufa de camping','Según la salida','grupo','Permite preparar comidas sin depender de una fogata.','Elige un modelo estable y revisa qué combustibles permite el lugar.','Usa solo al aire libre, conforme al fabricante; nunca dentro de la tienda.'],
['combustible','Combustible compatible','Según la salida','grupo','Alimenta la estufa seleccionada.','Verifica compatibilidad y cantidad para el menú; sigue las condiciones de transporte del fabricante.','Revisa conexiones antes del viaje y respeta las restricciones locales.'],
['ollas','Ollas y utensilios','Según la salida','grupo','Para cocinar el menú elegido.','Selecciona tamaños según porciones y estabilidad de la estufa.','Agrupa en una caja para facilitar montaje y limpieza.'],
['vajilla','Plato, taza y cubiertos','Esencial','persona','Vajilla reutilizable para cada integrante.','Prioriza durabilidad y facilidad de limpieza.','Identifica los juegos para no duplicar equipo.'],
['lavado','Kit de lavado','Esencial','grupo','Permite limpiar y guardar los utensilios.','Lleva recipiente, esponja, paño y productos permitidos en el sitio.','Usa los puntos autorizados; un jabón biodegradable no debe verterse directamente en cuerpos de agua.']]],
['Orientación y comunicación',[
['mapa','Ruta, mapas y reserva','Esencial','grupo','Facilitan llegar al sitio y orientarse en las salidas.','Descarga ruta, ubicación, reglas del camping y comprobante si aplica.','Revisa acceso y cobertura; guarda una alternativa consultable sin conexión.'],
['energia','Teléfono, cargadores y batería','Esencial','grupo','Mantienen disponibles la comunicación y la información del viaje.','Comprueba compatibilidad, carga y consumo esperado.','Una batería no garantiza cobertura; confirma cómo pedir ayuda desde el destino.']]],
['Iluminación',[
['frontal','Linterna frontal','Esencial','persona','Permite moverse con las manos libres de noche.','Comprueba autonomía, modo de uso y ajuste.','Prueba cada unidad y lleva recarga o baterías compatibles.'],
['farol','Farol de campamento','Confort','grupo','Ilumina el espacio de convivencia.','Prefiere iluminación controlable y adecuada al espacio.','Respeta horarios y evita iluminar los campamentos vecinos.']]],
['Baño portátil y desechos',[
['carpa-bano','Carpa de baño o privacidad','Según la salida','grupo','Da privacidad al utilizar un inodoro portátil o cambiarse de ropa. La carpa por sí sola no resuelve la recolección de desechos.','Comprueba altura, ventilación, espacio para el inodoro y anclajes. Elige un lugar permitido, separado del área de cocina y con acceso sencillo para el grupo.','Prueba el montaje y fija la carpa según su fabricante. Si el camping tiene baños adecuados y no necesitas privacidad adicional, marca No aplica.'],
['inodoro','Inodoro o excusado portátil','Según la salida','grupo','Resuelve el uso del baño cuando no hay sanitarios disponibles, siempre que el lugar permita ese sistema.','Elige entre un sistema con bolsas sanitarias compatibles y uno con depósito. Revisa estabilidad, capacidad, facilidad de limpieza y dónde podrás entregar o vaciar los residuos antes de comprar o salir.','No vacíes el depósito en el suelo, cuerpos de agua o cualquier sanitario sin autorización. Usa únicamente el punto de descarga que acepte ese sistema.'],
['consumibles-bano','Bolsas sanitarias o insumos del inodoro','Según la salida','grupo','Permiten recolectar los residuos conforme al tipo de inodoro. No todos los sistemas utilizan los mismos consumibles.','Para sistemas de bolsa, usa productos diseñados para residuos humanos; para depósitos, sigue los insumos y dosis del fabricante. Calcula repuestos según personas, duración y capacidad indicada.','No sustituyas las bolsas sanitarias por bolsas comunes. Confirma qué instalación acepta el residuo resultante; no lo arrojes a letrinas ni a contenedores que no lo admitan.'],
['transporte-residuos','Contención y transporte de residuos sanitarios','Según la salida','grupo','Ayuda a retirar los residuos de forma segura hasta un punto que los acepte.','Usa el cierre y la contención previstos por el sistema; si requiere contenedor exterior, verifica que sea resistente y estanco. Transporta separado de alimentos y agua potable.','Comprueba cierres y la ruta de disposición antes de regresar. La basura común, los residuos sanitarios y las aguas usadas pueden requerir destinos distintos.'],
['lavamanos','Estación de lavado de manos','Según la salida','grupo','Permite lavarse las manos cuando no hay un lavamanos disponible.','Prepara recipiente con llave, agua, jabón y forma de recoger el agua usada. Mantén esta estación separada del equipo para lavar platos.','Planea la recolección y disposición del agua usada conforme a las reglas del lugar. Evita que se derrame junto a la tienda o llegue a ríos y lagos.'],
['aguas-grises','Recipiente para aguas de lavado','Según la salida','grupo','Recoge el agua usada al lavar utensilios o manos cuando el lugar requiere retirarla.','Usa un recipiente identificable, con tapa y capacidad adecuada. Separa antes los restos sólidos de comida y colócalos en la bolsa de residuos correspondiente.','Vacía solo en un punto autorizado. No reutilices este recipiente para agua potable ni descargues jabón o restos de comida en cuerpos de agua.']]],
['Salud e higiene',[
['botiquin','Botiquín y medicamentos personales','Esencial','grupo','Reúne los suministros y tratamientos personales necesarios para el grupo.','Revisa contenido, caducidad y necesidades individuales antes de viajar.','Conserva medicamentos conforme a sus indicaciones; el checklist no sustituye formación ni atención médica.'],
['higiene','Aseo personal y papel higiénico','Esencial','persona','Ayuda a mantener la higiene durante la estancia.','Ajusta el kit a los servicios confirmados del camping.','Si no hay sanitarios, consulta antes el sistema de manejo de residuos humanos autorizado.'],
['repelente','Repelente de insectos','Según la salida','grupo','Puede ser útil según el entorno y la temporada.','Elige productos apropiados para los integrantes y consulta su etiqueta.','Respeta indicaciones de edad y uso del fabricante.'],
['basura','Bolsas y gestión de residuos','Esencial','grupo','Permiten recoger y retirar los residuos del grupo.','Prepara bolsas resistentes y separación si existe disposición adecuada.','Almacena comida y basura según las reglas locales de fauna.']]],
['Reparación y herramientas',[
['reparacion','Kit de reparación','Esencial','grupo','Resuelve fallos menores del equipo que conoces.','Incluye piezas compatibles con tienda, colchón y elementos que lleves.','Comprueba que sabes utilizar cada reparación antes de depender de ella.'],
['herramientas','Herramienta multiusos','Según la salida','grupo','Apoyo para ajustes sencillos.','Elige solo funciones necesarias y respeta las reglas del sitio.','Guarda herramientas fuera del alcance de menores; no implica permiso para cortar vegetación.']]],
['Organización y convivencia',[
['sillas','Sillas y mesa','Confort','grupo','Hacen más cómoda la convivencia.','Verifica qué mobiliario ofrece el camping y cuánto cabe en el vehículo.','Anota número de sillas; revisa estabilidad y carga admitida.'],
['cajas','Cajas y bolsas organizadoras','Confort','grupo','Separan cocina, descanso y objetos de uso frecuente.','Dimensiona con el espacio real del vehículo.','Deja accesibles refugio, abrigo e iluminación al llegar.'],
['juegos','Juegos y actividades','Confort','grupo','Opciones de convivencia para distintas edades.','Elige actividades adecuadas al lugar y al grupo.','Incluye una alternativa para lluvia sin ocupar demasiado espacio.']]]
];
const checks={
'Antes de salir':['Confirmar reserva, acceso y horarios del camping.','Consultar pronóstico y condiciones del terreno.','Verificar agua potable, baños y servicios disponibles.','Revisar reglas sobre fuego, mascotas y almacenamiento de comida.','Compartir destino y horario de regreso con una persona de confianza.','Revisar vehículo, combustible y forma de pedir ayuda.'],
'Al instalarse':['Elegir una superficie permitida y revisar el entorno.','Montar y asegurar el refugio antes de que oscurezca.','Organizar agua, alimentos, residuos e iluminación.','Acordar con el grupo los límites y un punto de encuentro.'],
'Al regresar':['Recoger residuos y revisar que no quede equipo.','Secar, limpiar y revisar el material.','Anotar faltantes, reparaciones y cosas que no se usaron.']};
const compareData=[
['Camping con coche',1,1,5,1,'No aplica'],['Backpacking',3,3,3,4,'6–12 kg'],['Bushcraft',2,5,3,2,'8–15 kg'],['Ultraligera',5,4,2,5,'< 5 kg de peso base'],['Travesía de larga distancia',4,4,2,5,'4,5–8 kg'],['Acampada dispersa',3,3,2,3,'6–12 kg, a pie'],['Acampada libre',4,4,2,4,'6–12 kg, a pie'],['Acampada en hamaca',4,3,4,4,'5–10 kg'],['Bikepacking',4,4,2,5,'4–9 kg sobre la bici'],['Kayak o canoa',2,4,4,2,'10–25 kg en bolsas estancas'],['Campamento Scout',2,3,4,1,'No aplica'],['Campamento de Manada',1,2,4,1,'No aplica']
];
