/* Copia offline de la pestaña “Videos” de Contenido del sitio.
   Se carga después de drive-content.js para conservar una sola fuente editable. */
DRIVE_SITE_CONTENT.videos = [
  ['Técnicas de campismo','lkyYT_IhsDk','Sellador de pintura vs. impermeabilizante para tiendas de campaña','Mantenimiento de equipo','Video de YouTube'],
  ['Técnicas de campismo','JdF0FJ0bi0s','Reparación de postes de tienda o casa de campaña','Mantenimiento de equipo','Video de YouTube'],
  ['Técnicas de campismo','klq_hwdJd4c','Reimpermeabiliza tu tienda de campaña · Nikwax Tent & Gear','Mantenimiento de equipo','Video de YouTube'],
  ['Técnicas de campismo','Dg6QOMleD5o','Cómo reparar malla o mosquitero de tienda o casa de campaña','Mantenimiento de equipo','Video de YouTube'],
  ['Técnicas de campismo','BSY4E3g4YHQ','Reparación de toldo o huella de tienda · Gear Aid Repair Tape','Mantenimiento de equipo','Video de YouTube'],
  ['Técnicas de campismo','MzRiI0ytFqM','Cómo instalar Coleman Instant Tent para 8 personas','Tiendas de campaña','Video de YouTube'],
  ['Técnicas de campismo','q4wkpBTLdZM','Cómo disminuir la condensación en una tienda de campaña','Tiendas de campaña','Video de YouTube'],
  ['Camping con coche','v3b2SwFLEJM','Cómo instalar Arpenaz Family 4.1 F&B Quechua','Tiendas de campaña','Video de YouTube'],
  ['Técnicas de campismo','EWvfVxb9JTI','Arma tu casa de campaña · guía para niños','Tiendas de campaña','Video de YouTube'],
  ['Técnicas de campismo','CIrwbFW72fk','Cómo elegir tu sleeping bag o bolsa de dormir','Sacos de dormir','Video de YouTube'],
  ['Técnicas de campismo','YXQddwtFLk0','Cómo guardar y transportar tu sleeping bag técnico','Sacos de dormir','Video de YouTube'],
  ['Técnicas de campismo','FvLxxc8hrcQ','Nuestras recomendaciones para dormir calientito en camping','Sacos de dormir','Video de YouTube'],
  ['Técnicas de campismo','Es82QAg1gys','Extiende el rango térmico de tu bolsa de dormir','Sacos de dormir','Video de YouTube'],
  ['Bushcraft','vIJZS9yTE3g','¿Qué llevar en una mochila para el monte?','Mochilas','Video de YouTube'],
  ['Técnicas de campismo','UEEO2BJDIyM','Iniciadores de fuego caseros para camping','Fogatas y fuego','Video de YouTube'],
  ['Técnicas de campismo','544RfjLz0Qg','Restaura la impermeabilidad de tu mochila','Mantenimiento de equipo','Video de YouTube'],
  ['Técnicas de campismo','M6-9N9WIc94','Tipos de fogatas básicas y para qué sirven','Fogatas y fuego','Video de YouTube'],
  ['Técnicas de campismo','H0h5B-UxwN8','Cómo doblar ropa y ahorrar espacio','Organización y hacks','Video de YouTube'],
  ['Técnicas de campismo','IgDUkKfkZ6Y','Cómo conectar una estufa de camping a tanque de gas','Cocina de campamento','Video de YouTube'],
  ['Camping con coche','rffe2D_1Nbs','Fogata familiar y campamento a 6 °C','Fogatas y fuego','Video de YouTube'],
  ['Camping con coche','PB42UAHTS1s','Setup de cocina en fogata','Cocina de campamento','Video de YouTube'],
  ['Camping con coche','07FCRUUbIvs','Camping en Zirahuén','Experiencias y lugares','Video de YouTube'],
  ['Camping con coche','DWO1Og32bNk','Coleman Kids 50: bolsa de dormir infantil','Sacos de dormir','Video de YouTube'],
  ['Camping con coche','S-fV50RlOu4','Coleman Plum Fun: bolsa de dormir juvenil','Sacos de dormir','Video de YouTube'],
  ['Mochilero o Backpacking','4s7kJTia7Y4','Bolsa de dormir infantil de verano','Sacos de dormir','Video de YouTube'],
  ['Campamento Scout · Manada','HxDVdis9f7E','Cómo armar la mochila de campamento para Manada','Mochilas','Video de YouTube'],
  ['Bushcraft','EAIb58gMdQI','Tienda Bushcraft Bungalow 2.0 OneTigris','Refugios y tiendas','Video de YouTube'],
  ['Campamento Scout · Manada','pvqQnnJYzuk','Cómo armar la mochila de ataque','Mochilas','Video de YouTube'],
  ['Mochilero o Backpacking','NT6muu9--74','Mochila SKALA 40 L','Mochilas','Video de YouTube'],
  ['Camping con coche','S0y6ajbTrKg','Qué llevamos para ir de camping','Guías y listas','Video de YouTube'],
  ['Mochilero o Backpacking','Zfd6RlcPW8U','Botella Nalgene: hidratación en ruta','Hidratación y accesorios','Video de YouTube'],
  ['Camping con coche','szYlu32mnRs','Estufa BRS-32','Cocina de campamento','Video de YouTube'],
  ['Mochilero o Backpacking','yx37Zqd7LhI','Forclaz Trek 100','Equipo técnico','Video de YouTube'],
  ['Campamento Scout · Manada','s_mGc2RxzLE','My First Victorinox','Herramientas y navajas','Video de YouTube'],
  ['Campamento Scout · Manada','kwzz3iC6FlY','Derechos de niñas y niños','Formación Scout','Video de YouTube'],
  ['Campamento Scout · Manada','EalEwet0Jm8','Deberes de niñas y niños','Formación Scout','Video de YouTube'],
  ['Camping con coche','W814l_xkHjY','Historia de una salida de camping','Historias de campismo','Video de YouTube'],
  ['Técnicas de campismo','LZ2WI9J52ds','Llegamos a 1000','Historias de campismo','Video de YouTube'],
  ['Camping con coche','MzRiI0ytFqM','Cómo instalar Coleman Instant Tent para 8 personas','Tiendas de campaña','Video de YouTube'],
  ['Camping con coche','IgDUkKfkZ6Y','Cómo conectar una estufa de camping a tanque de gas','Cocina de campamento','Video de YouTube'],
  ['Técnicas de campismo','rffe2D_1Nbs','Fogata familiar y campamento a 6 °C','Fogatas y fuego','Video de YouTube'],
  ['Técnicas de campismo','PB42UAHTS1s','Setup de cocina en fogata','Cocina de campamento','Video de YouTube'],
  ['Campamento Scout · Manada','EWvfVxb9JTI','Arma tu casa de campaña · guía para niños','Tiendas de campaña','Video de YouTube'],
  ['Mochilero o Backpacking','YXQddwtFLk0','Cómo guardar y transportar tu sleeping bag técnico','Sacos de dormir','Video de YouTube'],
  ['Mochilero o Backpacking','Es82QAg1gys','Extiende el rango térmico de tu bolsa de dormir','Sacos de dormir','Video de YouTube'],
  ['Mochilero o Backpacking','vIJZS9yTE3g','¿Qué llevar en una mochila para el monte?','Mochilas','Video de YouTube'],
  ['Bushcraft','UEEO2BJDIyM','Iniciadores de fuego caseros para camping','Fogatas y fuego','Video de YouTube'],
  ['Mochilero o Backpacking','544RfjLz0Qg','Restaura la impermeabilidad de tu mochila','Mantenimiento de equipo','Video de YouTube'],
  ['Bushcraft','M6-9N9WIc94','Tipos de fogatas básicas y para qué sirven','Fogatas y fuego','Video de YouTube'],
  ['Campamento Scout · Manada','DWO1Og32bNk','Coleman Kids 50: bolsa de dormir infantil','Sacos de dormir','Video de YouTube'],
  ['Campamento Scout · Tropa','S-fV50RlOu4','Coleman Plum Fun: bolsa de dormir juvenil','Sacos de dormir','Video de YouTube'],
  ['Campamento Scout · Tropa','4s7kJTia7Y4','Bolsa de dormir infantil de verano','Sacos de dormir','Video de YouTube'],
  ['Bushcraft','NT6muu9--74','Mochila SKALA 40 L','Mochilas','Video de YouTube'],
  ['Técnicas de campismo','Zfd6RlcPW8U','Botella Nalgene: hidratación en ruta','Hidratación y accesorios','Video de YouTube'],
  ['Acampada ultraligera','yx37Zqd7LhI','Forclaz Trek 100','Equipo técnico','Video de YouTube'],
  ['Bushcraft','s_mGc2RxzLE','My First Victorinox','Herramientas y navajas','Video de YouTube']
];
