/* Módulos técnicos de profundización. El enfoque cambia por modalidad para
   evitar que camping familiar, mochila, bushcraft y ultraligero se expliquen igual. */
const PROFESSIONAL_GUIDE_TOPICS = {
  coche: [
    ['Dormir caliente: aislante, bolsa y usuario', `<p>El sistema de dormir tiene dos barreras distintas: la bolsa reduce la pérdida de calor hacia el aire y el aislante limita la pérdida hacia el suelo. Compara colchonetas por su <strong>valor R</strong>: a mayor R, mayor resistencia térmica. El estándar ASTM F3340 permite comparar modelos que declaran haber sido ensayados con el mismo método; no convierte el resultado en una temperatura garantizada.</p><p>En bolsas de dormir revisa primero la etiqueta <strong>ISO 23537</strong>. “Comfort” orienta a una persona más friolenta y “Limit” a una persona menos friolenta en condiciones controladas. La norma no predice bien el desempeño infantil, de modo que para niñas y niños se necesita un margen conservador, ropa seca y supervisión. La temperatura extrema no es una referencia de compra para dormir cómodamente.</p><ul><li><strong>Espuma de celda cerrada:</strong> resistente, económica y ligera; ocupa volumen y ofrece menos comodidad.</li><li><strong>Autoinflable:</strong> combina espuma y aire; suele equilibrar comodidad, aislamiento y reparación.</li><li><strong>Inflable:</strong> muy cómoda y compacta; confirma R, lleva parche y evita usarla sin protección sobre suelo abrasivo.</li></ul><p class="technical-source">Referencias: ASTM F3340 e ISO 23537.</p>`],
    ['Tienda familiar: columna de agua, tejido y ventilación', `<p>La <strong>columna de agua</strong>, expresada en milímetros, indica la presión de agua que un tejido soporta en una prueba de laboratorio antes de filtrar. Sirve para comparar telas nuevas, pero no resume costuras, cierres, geometría, envejecimiento ni montaje. Un piso recibe presión por rodillas y colchones, por lo que suele necesitar una especificación y un cuidado distintos del toldo.</p><p>El <strong>nylon</strong> ofrece buena resistencia por peso y puede absorber humedad o destensarse; el <strong>poliéster</strong> suele estirar menos con lluvia y resistir mejor la radiación UV, aunque su desempeño depende del denier, tejido, recubrimiento y construcción. Silicona, poliuretano y otros tratamientos cambian impermeabilidad, tacto, reparación y vida útil. Comprueba si las costuras están selladas y prueba la tienda con lluvia controlada antes del viaje.</p><p>La condensación es vapor del interior que llega a una superficie fría. Ventila alto y bajo, separa colchones de las paredes y evita cocinar dentro. Ninguna cifra de impermeabilidad elimina la necesidad de ventilación.</p>`],
    ['Capas de ropa para una familia', `<p>Organiza la ropa por función. La <strong>capa base</strong> gestiona el sudor; la <strong>capa térmica</strong> retiene aire; la <strong>capa exterior</strong> protege de viento y precipitación. El algodón mojado tarda en secar, por lo que no debe ser la única estrategia de abrigo en clima frío o húmedo. Conserva ropa y calcetines secos exclusivamente para dormir.</p><p>Plumón y aislamiento sintético no son equivalentes. El plumón de buena calidad ofrece mucha calidez con poco peso y volumen, pero pierde rendimiento si se moja y suele costar más. El sintético tolera mejor humedad y seca antes, a cambio de mayor peso y volumen. En camping con coche puede ser más sensato priorizar facilidad de lavado, espacio y humedad real que pagar por la opción más ligera.</p>`],
    ['Cocina, hielera o nevera y agua', `<p>Planifica por comida y por persona: ingredientes, agua de preparación, combustible, utensilio y residuo resultante. Mantén alimentos fríos a 4 °C o menos; usa un termómetro dentro de la hielera o nevera, separa alimentos crudos de los listos para comer y limita aperturas. Una hielera llena conserva mejor la temperatura que una casi vacía.</p><p>Compara ollas por capacidad y sistema completo. El aluminio distribuye bien el calor y suele ser económico; el acero resiste abuso y pesa más; el titanio ahorra peso, pero conduce el calor de forma menos uniforme y puede quemar alimentos si se cocina algo más complejo que agua. La estufa se usa al aire libre, estable y según su manual; nunca dentro de la tienda, vestíbulo o vehículo.</p>`],
    ['Sanitario sin baño y botiquín útil', `<p>Si no hay sanitario, averigua antes cuál sistema admite el lugar: baño portátil con depósito, bolsas de residuos humanos certificadas o método de campo autorizado. Una carpa de privacidad no resuelve la disposición; el contenido debe sellarse, transportarse y descargarse donde corresponda. Papel, toallitas y productos de higiene regresan contigo cuando así lo exige el sitio.</p><p>El botiquín se diseña según integrantes, distancia a ayuda y formación. Como base incluye guantes, gasas, apósitos, cinta médica, vendas, antiséptico apropiado, pinzas, tijeras, tratamiento de ampollas, manta de emergencia y medicamentos personales con instrucciones. Añade una tarjeta con alergias, contacto, ubicación y hora de salida. Revisa caducidades y practica cómo pedir ayuda; llevar material que nadie sabe usar no crea capacidad.</p>`]
  ],
  senderismo: [
    ['Peso base, peso total y límites de la mochila', `<p>El <strong>peso base</strong> excluye agua, comida y combustible; el <strong>peso total al salir</strong> sí representa lo que cargarás. Pesa ambos y calcula el tramo con mayor agua. La meta no debe ser un porcentaje rígido del peso corporal: condición, ajuste, desnivel, experiencia, duración y lesiones cambian la carga tolerable.</p><p>Comprueba la capacidad nominal y el límite de carga de la mochila. Ajusta primero la longitud de torso, después el cinturón sobre la cresta ilíaca y finalmente tirantes y estabilizadores. Los objetos densos viajan cerca de la espalda; sueño y ropa seca van protegidos dentro. Una mochila sin estructura puede funcionar con cargas pequeñas, pero deja de transferir bien el peso cuando se supera el diseño.</p>`],
    ['Refugios y tejidos para caminar', `<p>Evalúa el refugio por peso completo: cuerpo o tarp, piso, varillas, estacas, cuerdas, funda y reparación. El denier describe el grosor relativo del hilo, no la resistencia total. Nylon, poliéster, laminados y recubrimientos implican diferencias de estiramiento, absorción, costo, reparación y vida útil.</p><p>Una mayor columna de agua no garantiza una tienda mejor si las costuras, cremalleras o geometría fallan. Revisa espacio utilizable, manejo de condensación, estabilidad al viento y facilidad de montaje con manos frías. Practica el montaje y una reparación antes de hacer una ruta de varios días.</p>`],
    ['Sistema de sueño y temperatura real', `<p>Combina la clasificación Comfort/Limit de la bolsa con el valor R del aislante y las condiciones de la persona. Hambre, fatiga, humedad, viento y talla incorrecta reducen la sensación térmica. El plumón ofrece mejor relación calor-peso cuando puede mantenerse seco; el sintético da más tolerancia a humedad y uso descuidado.</p><p>Una colchoneta inflable necesita kit de reparación y una estrategia de respaldo. La espuma de celda cerrada es menos cómoda, pero resiste perforaciones, funciona como asiento y puede complementar otra colchoneta. Prueba el sistema completo una noche cerca de casa antes de depender de él.</p>`],
    ['Agua, tratamiento y capacidad entre fuentes', `<p>Un filtro de microfibra hueca no elimina necesariamente virus ni contaminantes químicos. Congelado con agua en su interior puede dañarse sin que sea visible; protégelo junto al cuerpo o dentro del sistema de dormir cuando haya riesgo. Ebullición, químicos y luz UV tienen tiempos, límites y requisitos diferentes.</p><p>Confirma fuentes recientes, calcula litros entre ellas y añade lo que exige la cocina. Lleva capacidad suficiente aunque no la llenes en todos los tramos. El plan debe incluir qué harás si una fuente está seca o turbia y cómo evitarás contaminar la entrada del recipiente limpio.</p>`],
    ['Capas, pies, navegación y botiquín', `<p>Regula capas antes de sudar en exceso y conserva un conjunto seco para dormir. Atiende un punto caliente en el pie antes de que se forme la ampolla: limpia, seca, protege y corrige calcetín, cordón o ajuste. El botiquín de ruta incluye tratamiento de ampollas, hemorragias, heridas, esguinces, frío/calor y medicamentos personales, dimensionado al tiempo de evacuación.</p><p>Navega con mapa y brújula además del dispositivo que uses; descarga cartografía y protege batería. Comparte itinerario, vehículo, integrantes y hora para activar ayuda. En zonas remotas, un comunicador satelital puede reducir la dependencia de cobertura móvil, pero requiere plan, suscripción y práctica.</p>`]
  ],
  bushcraft: [
    ['Filos: geometría antes que apariencia', `<p>El tipo de filo determina cómo entra la hoja en el material y cómo se mantiene. Un <strong>Scandi</strong> facilita controlar tallas de madera y afilar apoyando el bisel; un <strong>convexo</strong> conserva más material detrás del filo y tolera trabajo robusto; un filo plano o secundario puede cortar alimentos y materiales con eficiencia. Acero, tratamiento térmico, espesor y geometría trabajan juntos: ningún nombre de acero garantiza desempeño por sí solo.</p><p>Elige herramienta por tarea. Una sierra suele hacer cortes transversales con menos energía y riesgo que golpear con hacha. Usa funda, zona despejada y posición que mantenga el recorrido lejos del cuerpo. Evita batoning o palanca si el fabricante no lo contempla. Limpia, seca y protege aceros al carbono al terminar.</p><p class="technical-source">Referencia de geometrías: Morakniv Knife Knowledge.</p>`],
    ['Fuego como sistema controlado', `<p>Separa cuatro capacidades: preparar yesca, producir una brasa o llama, alimentar por tamaños y extinguir. Pedernal, ferrocerio, fósforos y fricción requieren materiales y técnica diferentes. Practica primero en un entorno controlado con agua lista y una alternativa de cocina.</p><p>Viento, sequía y reglas pueden hacer improcedente cualquier fuego. Usa el área designada, limita el tamaño a la función y nunca dejes brasas sin atención. Para cerrar, agrega agua, remueve, repite y comprueba con el dorso de la mano a distancia hasta que esté frío. Si no puedes extinguirlo por completo, no lo enciendas.</p>`],
    ['Refugio, cordaje y aislamiento', `<p>Un tarp no abriga por sí mismo: controla precipitación y viento. El aislante y la bolsa o manta aportan la barrera térmica. Practica configuraciones bajas para viento y más abiertas para ventilación, con puntos de anclaje que no dañen árboles. Lleva estacas o sistemas propios; no dependas de cortar vegetación.</p><p>Las estructuras con material natural consumen recursos y pueden dañar el terreno. Úsalas solo donde estén expresamente permitidas, con madera caída autorizada y desmontaje total. Mantén un refugio moderno de respaldo mientras aprendes.</p>`],
    ['Agua y recursos naturales sin suposiciones', `<p>La apariencia clara no indica agua segura. Selecciona un tratamiento que responda a los riesgos del lugar y conoce qué no elimina. Filtrar sedimento mejora el proceso, pero no neutraliza por sí mismo virus o químicos. No dependas de plantas u hongos como alimento o medicina sin identificación experta y conocimiento local.</p><p>Autosuficiencia también significa llevar raciones, agua, navegación y abrigo suficientes para no extraer recursos. La observación, el rastreo y la identificación pueden practicarse sin cortar ni consumir.</p>`],
    ['Botiquín y plan para herramientas', `<p>Además del material habitual, una práctica con filos o fuego exige capacidad para controlar hemorragias, cubrir quemaduras y evacuar. Incluye guantes, gasas, apósitos, venda, cinta, tijeras, manta y medicamentos personales; añade material solo si el grupo está formado para usarlo.</p><p>Establece quién supervisa, dónde está el botiquín, cómo se detiene la actividad y por qué ruta saldrían. Fatiga, alcohol, oscuridad y prisa son razones para guardar herramientas, no para terminar “un último corte”.</p>`]
  ],
  ultraligera: [
    ['Menos de 5 kg: una descripción, no una obligación', `<p>El umbral de 5 kg se refiere al peso base y sirve para describir un estilo, no para autorizar recortes de agua, alimento, abrigo, navegación o botiquín. Registra también consumibles y peso total. El objetivo profesional es reducir redundancias después de analizar ruta, clima, experiencia y consecuencias de falla.</p><p>Pesa cada sistema —refugio, sueño, cocina, ropa y seguridad— y busca primero los cambios grandes. Quitar diez accesorios pequeños rara vez corrige una tienda o mochila sobredimensionada. Prueba cada cambio en una salida corta y conserva registro de fallas y artículos sin uso.</p>`],
    ['Materiales ligeros: costo, cuidado y reparación', `<p>El menor peso suele comprarse con costo, menor margen de abuso o reparación más especializada. Tejidos finos de nylon o poliéster dependen de trama, denier y recubrimiento; los laminados reducen absorción y estiramiento, pero se pliegan y reparan de otra manera. No compares solo gramos: incluye estacas, cuerdas, piso y kit de reparación.</p><p>La mochila ligera debe soportar el peso total, no únicamente el base. Los modelos sin armazón requieren volumen compacto y carga moderada; una colchoneta de espuma puede ayudar a formar estructura. Si el cinturón deja de transferir carga o el contenido forma puntos duros, el sistema está fuera de su rango útil.</p>`],
    ['Titanio y cocina mínima', `<p>El titanio resiste corrosión y permite recipientes muy ligeros, pero distribuye peor el calor que el aluminio. Es excelente para hervir agua y preparaciones simples; para cocinar alimentos espesos exige llama baja y atención para evitar puntos quemados. El aluminio suele cocinar de forma más uniforme y cuesta menos; el acero tolera uso rudo a cambio de peso.</p><p>Compara el sistema entero: olla, tapa, soporte, estufa, combustible, encendedor y parabrisas permitido. Una estufa pequeña puede ser inestable con ollas grandes. Verifica compatibilidad y nunca uses combustible dentro del refugio.</p>`],
    ['Aislantes: R, comodidad y redundancia útil', `<p>La espuma de celda cerrada pesa poco, no se perfora y sirve como asiento o respaldo; es voluminosa y menos cómoda. Una colchoneta inflable ofrece espesor y compactación, pero depende de válvula, tejido y reparación. Una combinación corta de espuma e inflable puede sumar aislamiento y redundancia, aunque también suma peso.</p><p>Compara valor R bajo ASTM F3340 cuando esté disponible y relaciónalo con clima, usuario y bolsa. La temperatura de la bolsa no sustituye el aislamiento del suelo. Para niñas y niños aplica un margen conservador porque ISO 23537 no ofrece un modelo predictivo infantil.</p>`],
    ['Plumón o sintético: decidir por humedad y uso', `<p>El <strong>fill power</strong> describe el volumen que ocupa una cantidad de plumón bajo una prueba; ayuda a comparar eficiencia, pero la calidez final también depende de la cantidad de relleno, construcción y ajuste. Un plumón de alto poder puede ahorrar peso y volumen, siempre que se mantenga seco.</p><p>El sintético suele conservar mejor rendimiento húmedo, seca antes y cuesta menos, aunque pesa y ocupa más para una calidez similar. Elige según clima, capacidad de proteger el equipo y frecuencia de uso. Guarda cualquiera limpio, seco y sin compresión prolongada.</p>`]
  ],
  tropa: [
    ['Equipo de patrulla: módulo, responsable y verificación', `<p>Organicen cocina, refugio, agua, sanidad, botiquín y actividades como módulos. Cada módulo tiene inventario, responsable de salida, responsable de regreso y prueba previa. La cantidad depende de participantes y menú; llevar dos piezas sin combustible compatible o sin quien sepa usarlas no crea redundancia.</p><p>Registren peso y volumen de los módulos para repartirlos por capacidad. Material de patrulla y equipo personal se revisan en bazares separados. Al volver, documenten consumo, daño y reparación antes de almacenar.</p>`],
    ['Técnica progresiva de herramientas y fuego', `<p>La autorización adulta no sustituye competencia. Antes de usar una navaja, sierra, hacha o estufa, cada participante demuestra postura, zona de seguridad, entrega, funda y cierre. La progresión empieza con tareas sencillas y materiales controlados.</p><p>Para fuego, practiquen preparación, encendido y extinción como una sola técnica. Las reglas del lugar y el riesgo del día deciden si se realiza. El equipo de extinción queda listo antes del primer intento.</p>`],
    ['Botiquín y plan de emergencia de grupo', `<p>El botiquín grupal se adapta a participantes, actividad y tiempo de evacuación. Incluye control de hemorragias, heridas, ampollas, esguinces, quemaduras, exposición y medicamentos personales identificados. Debe acompañarlo una persona con formación vigente y un registro de salud accesible según las reglas del grupo.</p><p>El plan define coordenadas, acceso para vehículos, contacto, hora límite y quién acompaña al resto si una persona evacúa. Practiquen comunicación y conteo; el botiquín por sí solo no organiza la respuesta.</p>`]
  ],
  manada: [
    ['Autonomía observable y carga apropiada', `<p>El objetivo no es que el lobato cargue lo mismo que un adulto, sino que reconozca, encuentre y cuide su equipo. Practica una secuencia: extender, nombrar, agrupar, empacar, cargar, abrir y volver a guardar. Si no puede ubicar agua, impermeable, frontal o abrigo, la organización debe simplificarse.</p><p>Ajusta cada mochila con la carga real y observa postura, equilibrio y fatiga. La mochila de ataque contiene solo lo necesario durante la actividad; la de campamento permanece organizada. El equipo pesado o de respuesta adulta se distribuye entre responsables.</p>`],
    ['Descanso infantil con margen conservador', `<p>Las temperaturas ISO de bolsas de adulto no predicen con precisión el descanso infantil. Revisa talla, espacio sobrante, aislante con valor R, pijama seco, gorro si corresponde y capacidad de avisar que siente frío. No uses la cifra “extrema” como objetivo.</p><p>Prueben el sistema completo en casa o en una noche controlada. El lobato practica cerrar la bolsa, usar el aislante y guardar todo al día siguiente. Un adulto verifica humedad, frío y ventilación durante el campamento.</p>`],
    ['Ficha de salud y botiquín bajo responsabilidad adulta', `<p>La ficha de salud, alergias, medicamentos y contactos viajan protegidos y bajo el protocolo de responsables. Los medicamentos personales no se mezclan con material general ni se dejan en la mochila del menor sin un plan acordado.</p><p>El botiquín adulto cubre heridas, ampollas, esguinces, quemaduras y exposición según el programa. Los lobatos aprenden a avisar, mantenerse con el grupo y señalar la ubicación; la valoración y administración corresponden a responsables capacitados.</p>`]
  ]
};

const PROFESSIONAL_RESOURCE_TOPICS = {
  tecnicas: [
    ['Cómo leer especificaciones sin confundirlas', `<p>Una especificación solo es comparable cuando mide lo mismo bajo un método conocido. Valor R describe resistencia térmica; columna de agua describe presión hidrostática; denier describe hilo; Comfort y Limit pertenecen a una prueba de bolsas. Ninguna cifra resume por sí sola el desempeño completo.</p><p>Antes de enseñar una técnica, identifica la norma o método, la condición de prueba y lo que queda fuera. Después valida con una práctica controlada y registra el resultado. Así se evita convertir una cifra de laboratorio en una promesa universal.</p>`, []],
    ['Prueba, mantenimiento y reparación', `<p>Usa una secuencia repetible: inspeccionar, limpiar según fabricante, probar en condiciones controladas, reparar, volver a probar y registrar. Una reparación de campo debe permitir terminar o evacuar; una reparación permanente requiere material compatible y tiempo de curado.</p><p>Documenta modelo, material, daño, producto aplicado y fecha. El video muestra el procedimiento; la ficha debe explicar compatibilidad, límite y señal para retirar el equipo.</p>`, []]
  ],
  reviews: [
    ['Matriz profesional para evaluar equipo', `<p>Cada review debe registrar uso previsto, usuarios, peso completo, dimensiones, materiales, especificaciones relevantes, montaje, mantenimiento, reparación, garantía y precio observado. Después separa lo declarado por el fabricante de lo observado por la familia.</p><p>La conclusión responde “¿para quién y bajo qué condiciones funciona?” y no “¿cuál gana?”. Peso, costo, comodidad y durabilidad forman un intercambio: mejorar uno suele afectar otro. Indica fecha y versión porque productos y precios cambian.</p>`, []],
    ['Qué probar antes de recomendar', `<p>Comprueba la función principal y los puntos de falla: una tienda se monta, ventila y moja de forma controlada; una mochila se ajusta con carga; una bolsa se evalúa con aislante y usuario; una estufa se prueba con olla y combustible compatibles. No extrapoles una salida tranquila a viento, frío o lluvia que no se observaron.</p><p>Registra limitaciones, reparabilidad y experiencia a largo plazo. Si un dato no fue medido, preséntalo como pendiente en vez de estimarlo.</p>`, []]
  ]
};
